name = "yagiz"
pages_build_output_dir = "dist"
compatibility_date = "2025-12-01"
compatibility_flags = [ "nodejs_compat" ]
send_metrics = false

[placement]
mode = "smart"

[vars]
MAILJET_CONTACT_LIST_ID = "70041"
NODE_VERSION = "20"

[env.production]
compatibility_date = "2025-12-01"
compatibility_flags = [ "nodejs_compat" ]

[env.production.vars]
MAILJET_CONTACT_LIST_ID = "70041"
NODE_VERSION = "20"
